using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class animationStateController : MonoBehaviour
{
    Animator animator;
    float velocity = 0.0f;
    public float acceleration = 0.1f;
    public float deceleration = 0.5f;
    int VelocityHash;
 
    // Start is called before the first frame update
    void Start()
    {
        //Reference to animator
        animator = GetComponent<Animator>();

        //Optimization
        VelocityHash = Animator.StringToHash("Velocity");
        
    }

    // Update is called once per frame
    void Update()
    {
        //Get key input
        bool forwardPressed = Input.GetKey(KeyCode.W);

        if (forwardPressed && velocity < 1.0f)
        {
            velocity += Time.deltaTime * acceleration;
        }
        if (!forwardPressed && velocity > 0.0f)
        {
            velocity -= Time.deltaTime * deceleration;
        }
        if (!forwardPressed && velocity < 0.0f)
        {
            velocity = 0.0f;
        }

        animator.SetFloat(VelocityHash, velocity);
        
    }
}
